site_name: hoa-tools
site_url: https://hoa-tools.readthedocs.io
repo_url: https://github.com/HumanOrganAtlas/hoa-tools
repo_name: hoa-tools
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    # Palette toggle for light mode

    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      toc_depth: 3

plugins:
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv

          options:
            docstring_style: numpy
            show_root_toc_entry: false
            show_object_full_path: false
            group_by_category: true
            heading_level: 3
            show_symbol_type_heading: true
            separate_signature: true
            show_source: false
            show_signature_annotations: true
            signature_crossrefs: true
            show_if_no_docstring: true
            filters:
              # Skip anything starting with "_"
              - "!^_"
            extensions:
              - griffe_pydantic:
                  schema: false

nav:
  - Home: index.md
  - Tutorial:
      - tutorial/index.md
      - Inventory: tutorial/inventory.py
      - Datasets: tutorial/dataset.py
      - Getting data: tutorial/fetching_data.py
      - Sub-volumes: tutorial/vois.py
      - Registration: tutorial/registration.py
  - How do I...?: how_to.md
  - API reference:
      - api/index.md
      - dataset: api/dataset.md
      - inventory: api/inventory.md
      - metadata: api/metadata.md
      - types: api/types.md
      - voi: api/voi.md
  - Release notes: release-notes.md
  - Development: development.md

watch:
  - src
