[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
]

[project]
authors = [
    {email = "d.stansby@ucl.ac.uk", name = "David Stansby"},
]
classifiers = [
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]
dependencies = [
    "pandas",
]
description = "Tools for working with the Human Organ Atlas"
dynamic = [
    "version",
]
keywords = [
]
name = "hoa-tools"
optional-dependencies = {dev = [
    "build",
    "mypy",
    "pre-commit",
    "ruff",
    "tox",
    "twine",
], docs = [
    "pydata-sphinx-theme",
    "sphinx",
    'numpydoc',
    'sphinx-automodapi',
], test = [
    "pytest",
    "pytest-cov",
]}
readme = "README.md"
requires-python = ">=3.10"
license.file = "LICENSE.md"
urls.homepage = "https://github.com/HumanOrganAtlas/hoa-tools"

[tool.coverage]
report = {sort = "cover"}
run = {branch = true, parallel = true, source = [
    "HOA Tools",
]}
paths.source = [
    "src",
    ".tox*/*/lib/python*/site-packages",
]

[tool.mypy]
explicit_package_bases = true

[tool.pytest.ini_options]
addopts = """
    --color=yes
    --import-mode=importlib
    --verbose
"""
testpaths = [
    "src/*",
]

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/hoa_tools/_version.py"

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false
