fix = true
force-exclude = true
target-version = "py311"

[lint]
ignore = [
  "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed in `**kwargs`
  "ARG001",  # Unused function argument
  "COM812",  # trailing commas (ruff-format recommended)
  "D200",    # One-line docstring should fit on one line
  "D100",    # No docstring in public module
  "D105",    # Missing docstring in magic method
  "D203",    # no-blank-line-before-class
  "D212",    # multi-line-summary-first-line
  "D401",    # First line of docstring should be in imperative mood
  "D407",    # removed dashes lines under sections
  "D417",    # argument description in docstring (unreliable)
  "ISC001",  # simplify implicit str concatenation (ruff-format recommended)
  "PD901",   # Avoid using the generic variable name `df` for DataFrames
  "PLR0913", # Too many arguments in function definition
  "N813",
  "N806",
  "A005",
  "EM101",
  "TRY003",
]
select = ["ALL"]
isort.known-first-party = ["HOA Tools"]
mccabe.max-complexity = 18
pep8-naming.classmethod-decorators = ["classmethod"]

[lint.per-file-ignores]
"docs/conf.py" = [
  "A001",   # Variable `copyright` is shadowing a Python builtin
  "ERA001", # Found commented-out code
  "FBT001", # Boolean-typed positional argument in function definition
]
"docs*" = [
  "INP001", # File is part of an implicit namespace package.
]
"docs/tutorial/*" = [
  "T201", # Allow print()
  "D100", # don't require docstring
  "B018",
  "E402",
  "E501",
]
"tests*" = [
  "D100",    # Missing docstring in public module
  "D103",    # Missing docstring in public function
  "INP001",  # File is part of an implicit namespace package.
  "PLR2004", # Magic value used in comparison
  "S101",    # Use of `assert` detected
]
# This is an autogenerated file
"src/hoa_tools/metadata.py" = ["E501", "TC003", "ERA001", "D101"]
